#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to meet the specified requirements.

# Function to install a package if it's not already installed
function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "$1 is already installed.\n"
    fi
}

# Install nginx
install nginx

# Allow nginx on port 80 through the firewall
sudo ufw allow 'Nginx HTTP'

# Set up directory and file structure
sudo mkdir -p /var/www/test/html
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www

# Create index.html
echo "Hello World!" > /var/www/test/html/index.html

# Create error page
echo "Ceci n'est pas une page" > /var/www/test/html/404.html

# Configure Nginx with the required settings
nginx_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root /var/www/test/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4';
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"

# Write the nginx configuration
echo "$nginx_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx service to apply changes
sudo service nginx restart

echo -e "Configuration complete. Nginx is running with custom HTTP header X-Served-By set to hostname."
