#!/usr/bin/env bash
# Install and configure HAProxy on an Ubuntu server to load balance between two web servers

STUDENT_ID="197045"

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Configure HAProxy
sudo bash -c "cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server ${STUDENT_ID}-web-01 54.160.94.43:80 check
    server ${STUDENT_ID}-web-02 34.203.38.175:80 check
EOF"

# Restart HAProxy to apply the changes
sudo service haproxy restart

# Check HAProxy status
sudo service haproxy status
