#!/usr/bin/env bash
# Script to ensure Nginx is installed, running, and listening on port 80

# Remove the existing symbolic link for the default site configuration
rm /etc/nginx/sites-enabled/default

# Create a new symbolic link for the default site configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
