#!/usr/bin/env bash
# This script iterates from 1 to 100 using a for loop. Inside the loop:

# It checks if the current number is divisible by both 3 and 5
# and prints "FizzBuzz" if true.
# If the number is only divisible by 3 (i % 3 == 0), it prints "Fizz".
# If the number is only divisible by 5 (i % 5 == 0), it prints "Buzz".
# Otherwise, it prints the number itself.

for ((i = 1; i <= 100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
