#!/usr/bin/env bash
# Script to configure an Ubuntu server with requirements below:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup the original hosts file
cp /etc/hosts ~/hosts.new

# Add localhost resolution to hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new

# Add facebook.com resolution to hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
